name: Build

on:
    pull_request: ~
    push: ~
    workflow_dispatch: ~
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday

jobs:
    tests:
        runs-on: ubuntu-latest
        name: "PHP ${{ matrix.php }}"
        strategy:
            fail-fast: false
            matrix:
                php: ["7.4", "8.0", "8.1"]

        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -   name: Install dependencies
                run: composer update

            -   name: Run analysis
                run: composer validate --strict

            -   name: Run static checks
                run: vendor/bin/psalm --php-version="${{ matrix.php }}"

            -   name: Run tests
                run: vendor/bin/behat --strict -vvv --no-interaction
